# Generated by Django 4.2.3 on 2023-12-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='support_ticket',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='support_ticket',
            name='problem',
            field=models.TextField(max_length=200),
        ),
    ]
